version: "3.9"

services:
  db:
    image: postgres:15  # Используем образ PostgreSQL версии 15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Том для хранения данных базы данных
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - quiz_network

  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"  # Миграции и запуск сервера
    volumes:
      - .:/app  # Монтируем проект в контейнер, заменяя /tests на /app
    ports:
      - "8000:8000"  # Пробрасываем порт 8000 для доступа из браузера
    depends_on:
      - db  # Зависимость от базы данных
    env_file:
      - .env  # Загружаем переменные окружения из .env
    networks:
      - quiz_network
    restart: always  # Перезапуск контейнера в случае сбоев
    working_dir: /app  # Устанавливаем рабочую директорию для контейнера

volumes:
  postgres_data:  # Том для данных базы данных

networks:
  quiz_network:  # Сеть для взаимодействия контейнеров
